const String CONTRACT_STATUS_WAITFORPAYMENT = "WAITFORPAYMENT";
const String CONTRACT_STATUS_SUCCESS = "SUCCESS";

const String PROCESS_ORDER_STATUS_PREORDER = 'PREORDER';
const String PROCESS_ORDER_STATUS_WAITFORCONFIRM = 'WAITFORCONFIRM';
const String PROCESS_ORDER_STATUS_INPROGRESS = 'INPROGRESS';
const String PROCESS_ORDER_STATUS_SUCCESS = 'SUCCESS';