// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAP2rxfTzwMgeCdf06-6otcSvnW9Y10I',
    appId: '1:252620116938:web:8b35cae1f0e9a8c81d3533',
    messagingSenderId: '252620116938',
    projectId: 'glopr-chat',
    authDomain: 'glopr-chat.firebaseapp.com',
    storageBucket: 'glopr-chat.appspot.com',
    measurementId: 'G-ZQQ7T8PLYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzEWKQPXYYE3JtqWISJkmRDpecdJ-fMw',
    appId: '1:252620116938:android:c24f5a086086c9031d3533',
    messagingSenderId: '252620116938',
    projectId: 'glopr-chat',
    storageBucket: 'glopr-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbls-xAYnFlCECMyPr0S4n3Qc-Bzmld58',
    appId: '1:252620116938:ios:9323ae25b5a893191d3533',
    messagingSenderId: '252620116938',
    projectId: 'glopr-chat',
    storageBucket: 'glopr-chat.appspot.com',
    iosClientId:
        '252620116938-5c88rndjdumf5ffe4410bp6gk16iju4q.apps.googleusercontent.com',
    iosBundleId: 'com.gloprtech.chatGlopr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbls-xAYnFlCECMyPr0S4n3Qc-Bzmld58',
    appId: '1:252620116938:ios:9323ae25b5a893191d3533',
    messagingSenderId: '252620116938',
    projectId: 'glopr-chat',
    storageBucket: 'glopr-chat.appspot.com',
    iosClientId:
        '252620116938-5c88rndjdumf5ffe4410bp6gk16iju4q.apps.googleusercontent.com',
    iosBundleId: 'com.gloprtech.chatGlopr',
  );
}
